# Generated by Django 3.1 on 2021-03-27 18:53

from django.db import migrations
import posts.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210305_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='sections',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('rows', wagtail.core.blocks.StreamBlock([('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link'], required=False))])), ('paragraph', posts.blocks.ParagraphBlock()), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.TextBlock())]))], required=True))]))]),
        ),
    ]
