# Generated by Django 3.1 on 2021-04-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_profession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiance',
            new_name='Experience',
        ),
    ]
